# Use postgres/example user/password credentials
version: '3.9'

volumes:
  postgres:
    driver: local

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      -  ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # Use root/example as user/password credentials

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z
